# Set the maximum line length to 120.
line-length = 120
target-version = "py311"

[lint]
select = ["E", "F", "W", "I", "ASYNC", "UP", "FLY", "PERF", "FURB", "ERA", "ANN", "PIE", "PL"]

ignore = ["E501", "PLR", "PLW"]

[lint.flake8-annotations]
allow-star-arg-any = true
